// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Assert non-null since Prisma expects a string. Ensure DATABASE_URL is set in your environment.
    url: process.env["DATABASE_URL"]!,
  },
});
